name: llm_finetune_cp
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libffi=3.4.2
  - libgomp=13.2.0
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - openssl=3.1.3
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.10.12
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13
  - wheel=0.41.2=pyhd8ed1ab_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.23.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bitsandbytes==0.41.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - datasets==2.9.0
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - evaluate==0.4.0
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - gitdb==4.0.10
    - gitpython==3.1.37
    - hjson==3.1.0
    - idna==3.4
    - joblib==1.3.2
    - multidict==6.0.4
    - multiprocess==0.70.14
    - ninja==1.11.1
    - nltk==3.8.1
    - pandas==2.1.1
    - pathtools==0.1.2
    - peft==0.5.0
    - protobuf==4.24.3
    - py-cpuinfo==9.0.0
    - pyarrow==13.0.0
    - pydantic==1.10.13
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - requests==2.31.0
    - responses==0.18.0
    - rouge-score==0.1.2
    - scipy==1.11.3
    - sentry-sdk==1.31.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.1
    - torch==2.0.1
    - tqdm==4.66.1
    - transformers==4.33.3
    - tzdata==2023.3
    - urllib3==2.0.5
    - wandb==0.15.11
    - xxhash==3.3.0
    - yarl==1.9.2
