wandb_version: 1

model:
  desc: null
  value: gpt-3.5-turbo-1106
dataset:
  desc: null
  value: 1
task:
  desc: null
  value: 1
epochs:
  desc: null
  value: 3
temp:
  desc: null
  value: 0.0
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713213746.0
    t:
      1:
      - 5
      - 49
      - 51
      - 53
      - 55
      - 95
      2:
      - 5
      - 49
      - 51
      - 53
      - 55
      - 95
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
